// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Terminal

#ifndef _TERMINAL_UI_H
#define _TERMINAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void showanim_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Startpage
void ui_Startpage_screen_init(void);
void ui_event_Startpage(lv_event_t * e);
extern lv_obj_t * ui_Startpage;
extern lv_obj_t * ui_MainTitle;
void ui_event_Entry(lv_event_t * e);
extern lv_obj_t * ui_Entry;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Mainpage
void ui_Mainpage_screen_init(void);
void ui_event_Mainpage(lv_event_t * e);
extern lv_obj_t * ui_Mainpage;
void ui_event_weather(lv_event_t * e);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_Image2;
void ui_event_game(lv_event_t * e);
extern lv_obj_t * ui_game;
extern lv_obj_t * ui_Image3;
void ui_event_voice(lv_event_t * e);
extern lv_obj_t * ui_voice;
extern lv_obj_t * ui_Image4;
void ui_event_mpu(lv_event_t * e);
extern lv_obj_t * ui_mpu;
extern lv_obj_t * ui_Image5;
void ui_event_campass(lv_event_t * e);
extern lv_obj_t * ui_campass;
extern lv_obj_t * ui_Image7;
void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_weatherlabel;
extern lv_obj_t * ui_settinglabel;
extern lv_obj_t * ui_campasslabel;
extern lv_obj_t * ui_mpulabel;
extern lv_obj_t * ui_gamelabel;
extern lv_obj_t * ui_voicelabel;
extern lv_obj_t * ui_functionmenutitle;
// SCREEN: ui_weatherpage
void ui_weatherpage_screen_init(void);
void ui_event_weatherpage(lv_event_t * e);
extern lv_obj_t * ui_weatherpage;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_gamepage
void ui_gamepage_screen_init(void);
void ui_event_gamepage(lv_event_t * e);
extern lv_obj_t * ui_gamepage;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_voicepage
void ui_voicepage_screen_init(void);
void ui_event_voicepage(lv_event_t * e);
extern lv_obj_t * ui_voicepage;
extern lv_obj_t * ui_Label14;
// SCREEN: ui_mpupage
void ui_mpupage_screen_init(void);
void ui_event_mpupage(lv_event_t * e);
extern lv_obj_t * ui_mpupage;
extern lv_obj_t * ui_Label15;
// SCREEN: ui_campasspage
void ui_campasspage_screen_init(void);
void ui_event_campasspage(lv_event_t * e);
extern lv_obj_t * ui_campasspage;
extern lv_obj_t * ui_Label16;
// SCREEN: ui_settingpage
void ui_settingpage_screen_init(void);
void ui_event_settingpage(lv_event_t * e);
extern lv_obj_t * ui_settingpage;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui____initial_actions0;

extern lv_timer_t * my_lv_timer;
extern int strength;


LV_IMG_DECLARE(ui_img_944254084);    // assets/天气.png
LV_IMG_DECLARE(ui_img_227306801);    // assets/游戏手柄.png
LV_IMG_DECLARE(ui_img_988448286);    // assets/麦克风.png
LV_IMG_DECLARE(ui_img_613467726);    // assets/旋转.png
LV_IMG_DECLARE(ui_img_499049799);    // assets/陀螺仪完整.png
LV_IMG_DECLARE(ui_img_1887403499);    // assets/设置.png



LV_FONT_DECLARE(ui_font_Terminal);
LV_FONT_DECLARE(ui_font_Terminal22);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
