// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Terminal

#include "../ui.h"

static const char *TAG = "NET";

void ui_netapp_screen_init(void)
{
    ESP_LOGI(TAG, "网络应用界面初始化");
    ui_netapp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_netapp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_netapp, lv_color_hex(0x5295B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_netapp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_netapptitle = lv_label_create(ui_netapp);
    lv_obj_set_width(ui_netapptitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netapptitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_netapptitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_netapptitle, "NetApp");
    lv_obj_set_style_text_font(ui_netapptitle, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_netapp, ui_event_netapp, LV_EVENT_ALL, NULL);

}
