// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Terminal

#include "../ui.h"

static const char *TAG = "StartPage";

void ui_Startpage_screen_init(void)
{   
    // ESP_LOGI(TAG, "开始界面初始化");
    ui_Startpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Startpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Startpage, lv_color_hex(0x6D65A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Startpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainTitle = lv_label_create(ui_Startpage);
    lv_obj_set_width(ui_MainTitle, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_MainTitle, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_MainTitle, 3);
    lv_obj_set_y(ui_MainTitle, -45);
    lv_obj_set_align(ui_MainTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainTitle, "ESP32-C3 \n\n 多功能终端");
    lv_obj_set_style_text_color(ui_MainTitle, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MainTitle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MainTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainTitle, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Entry = lv_btn_create(ui_Startpage);
    lv_obj_set_width(ui_Entry, 120);
    lv_obj_set_height(ui_Entry, 50);
    lv_obj_set_x(ui_Entry, 0);
    lv_obj_set_y(ui_Entry, 40);
    lv_obj_set_align(ui_Entry, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Entry, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Entry, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Entry, lv_color_hex(0x126B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Entry, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Entry);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "进入");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifibtn = lv_btn_create(ui_Startpage);
    lv_obj_set_width(ui_wifibtn, 40);
    lv_obj_set_height(ui_wifibtn, 40);
    lv_obj_set_x(ui_wifibtn, 118);
    lv_obj_set_y(ui_wifibtn, 85);
    lv_obj_set_align(ui_wifibtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifibtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifibtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifibtn, lv_color_hex(0x6A65A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifibtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifibtn, &ui_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifibtn, lv_color_hex(0x6A65A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifibtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Entry, ui_event_Entry, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifibtn, ui_event_wifibtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Startpage, ui_event_Startpage, LV_EVENT_ALL, NULL);

}
