// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Terminal

#include "../ui.h"

// #define DEFAULT_SCAN_LIST_SIZE 10

// #define ESP_WIFI_MAXIMUM_RETRY 5

// #define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
// #define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_BOTH
// #define EXAMPLE_H2E_IDENTIFIER ""

// // #define EXAMPLE_ESP_WIFI_SSID "jialongfei"
// // #define EXAMPLE_ESP_WIFI_PASS "19981230"

// bool wifiswitch_flag = false;

// esp_netif_t *sta_netif;

// static char *ssid_list[DEFAULT_SCAN_LIST_SIZE];

// static EventGroupHandle_t s_wifi_event_group;

// #define WIFI_CONNECTED_BIT BIT0
// #define WIFI_FAIL_BIT BIT1

static const char *TAG = "WiFi";

// static int s_retry_num = 0;

// static void wifi_scan(void)
// {

//     wifi_init_config_t wifi_cfg = WIFI_INIT_CONFIG_DEFAULT();
//     ESP_ERROR_CHECK(esp_wifi_init(&wifi_cfg));

//     uint16_t number = DEFAULT_SCAN_LIST_SIZE;
//     wifi_ap_record_t ap_info[DEFAULT_SCAN_LIST_SIZE];
//     uint16_t ap_count = 0;
//     memset(ap_info, 0, sizeof(ap_info));

//     ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
//     ESP_ERROR_CHECK(esp_wifi_start());
//     esp_wifi_scan_start(NULL, true);
//     ESP_LOGI(TAG, "Max AP number ap_info can hold = %u", number);
//     ESP_ERROR_CHECK(esp_wifi_scan_get_ap_records(&number, ap_info));
//     ESP_ERROR_CHECK(esp_wifi_scan_get_ap_num(&ap_count));
//     ESP_LOGI(TAG, "Total APs scanned = %u, actual AP number ap_info holds = %u", ap_count, number);
//     // 创建一个包含所有 SSID 并以换行符分隔的字符串
//     for (int i = 0; i < number; i++)
//     {
//         ESP_LOGI(TAG, "SSID \t\t%s", ap_info[i].ssid);
//         ssid_list[i] = (char *)ap_info[i].ssid;
//         lv_dropdown_add_option(ui_wifiDropdown, ssid_list[i], i);
//     }
// }

// static void nvs_init(void)
// {
//     // Initialize NVS
//     esp_err_t ret = nvs_flash_init();
//     if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND)
//     {
//         ESP_ERROR_CHECK(nvs_flash_erase());
//         ret = nvs_flash_init();
//     }
//     ESP_ERROR_CHECK(ret);
// }

// static void switch_cb(lv_event_t *e)
// {
//     lv_obj_t *sw = lv_event_get_target(e);
//     if (lv_obj_has_state(sw, LV_STATE_CHECKED))
//     {
//         ESP_LOGI(TAG, "Wifi scan started");
//         wifiswitch_flag = true;
//         nvs_init();
//         lv_dropdown_clear_options(ui_wifiDropdown);
//         wifi_scan();
//         // my_lv_timer = lv_timer_create(wifi_scan, 500, NULL);
//     }
//     else
//     {
//         ESP_LOGI(TAG, "Wifi scan stopped");
//         wifiswitch_flag = false;
//         lv_led_off(ui_wifiled);
//         esp_wifi_stop();
//         esp_wifi_deinit();
//         // lv_dropdown_clear_options(ui_wifiDropdown);
//         lv_textarea_clear_selection(ui_passwordTextArea);
//     }
// }

// static void event_handler(void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
// {
//     ESP_LOGI(TAG, "Entry WiFi connect event_handler");
//     if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START)
//     {
//         esp_wifi_connect();
//     }
//     else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED)
//     {
//         if (s_retry_num < ESP_WIFI_MAXIMUM_RETRY)
//         {
//             esp_wifi_connect();
//             s_retry_num++;
//             ESP_LOGI(TAG, "retry to connect to the AP");
//         }
//         else
//         {
//             xEventGroupSetBits(s_wifi_event_group, WIFI_FAIL_BIT);
//         }
//         ESP_LOGI(TAG, "connect to the AP fail");
//     }
//     else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP)
//     {
//         ip_event_got_ip_t *event = (ip_event_got_ip_t *)event_data;
//         ESP_LOGI(TAG, "got ip:" IPSTR, IP2STR(&event->ip_info.ip));
//         s_retry_num = 0;
//         xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
//     }
// }

// void wifi_init_sta(const char *name, const char *password)
// {
//     s_wifi_event_group = xEventGroupCreate();

//     // ESP_ERROR_CHECK(esp_netif_init());

//     // ESP_ERROR_CHECK(esp_event_loop_create_default());
//     // esp_netif_create_default_wifi_sta();

//     wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
//     ESP_ERROR_CHECK(esp_wifi_init(&cfg));

//     esp_event_handler_instance_t instance_any_id;
//     esp_event_handler_instance_t instance_got_ip;
//     ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
//                                                         ESP_EVENT_ANY_ID,
//                                                         &event_handler,
//                                                         NULL,
//                                                         &instance_any_id));
//     ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT,
//                                                         IP_EVENT_STA_GOT_IP,
//                                                         &event_handler,
//                                                         NULL,
//                                                         &instance_got_ip));

//     wifi_config_t wifi_config = {
//         .sta = {
//             // .ssid = EXAMPLE_ESP_WIFI_SSID,
//             // .password = EXAMPLE_ESP_WIFI_PASS,
//             .ssid = "",
//             .password = "",
//             /* Authmode threshold resets to WPA2 as default if password matches WPA2 standards (pasword len => 8).
//              * If you want to connect the device to deprecated WEP/WPA networks, Please set the threshold value
//              * to WIFI_AUTH_WEP/WIFI_AUTH_WPA_PSK and set the password with length and format matching to
//              * WIFI_AUTH_WEP/WIFI_AUTH_WPA_PSK standards.
//              */
//             .threshold.authmode = ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD,
//             .sae_pwe_h2e = ESP_WIFI_SAE_MODE,
//             .sae_h2e_identifier = EXAMPLE_H2E_IDENTIFIER,
//         },
//     };

//     strncpy((char *)wifi_config.sta.ssid, name, sizeof(wifi_config.sta.ssid));
//     strncpy((char *)wifi_config.sta.password, password, sizeof(wifi_config.sta.password));

//     ESP_LOGI(TAG, "ssid: %s", wifi_config.sta.ssid);
//     ESP_LOGI(TAG, "password: %s", wifi_config.sta.password);

//     ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
//     ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
//     ESP_ERROR_CHECK(esp_wifi_start());

//     ESP_LOGI(TAG, "wifi_init_sta finished.");

//     /* Waiting until either the connection is established (WIFI_CONNECTED_BIT) or connection failed for the maximum
//      * number of re-tries (WIFI_FAIL_BIT). The bits are set by event_handler() (see above) */
//     EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group,
//                                            WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
//                                            pdFALSE,
//                                            pdFALSE,
//                                            portMAX_DELAY);

//     /* xEventGroupWaitBits() returns the bits before the call returned, hence we can test which event actually
//      * happened. */
//     if (bits & WIFI_CONNECTED_BIT)
//     {
//         ESP_LOGI(TAG, "connected to ap SSID:%s password:%s",
//                  wifi_config.sta.ssid, wifi_config.sta.password);

//         lv_led_on(ui_wifiled);
//     }
//     else if (bits & WIFI_FAIL_BIT)
//     {
//         ESP_LOGI(TAG, "Failed to connect to SSID:%s, password:%s",
//                  wifi_config.sta.ssid, wifi_config.sta.password);
//         lv_led_off(ui_wifiled);
//     }
//     else
//     {
//         ESP_LOGE(TAG, "UNEXPECTED EVENT");
//     }
// }

// static void wifi_linkbtn(lv_event_t *e)
// {

//     char wifiname[32];
//     lv_dropdown_get_selected_str(ui_wifiDropdown, wifiname, sizeof(wifiname));
//     ESP_LOGI(TAG, "Wifi SSID is %s\n", wifiname);
//     const char *pwd = lv_textarea_get_text(ui_passwordTextArea);
//     ESP_LOGI(TAG, "Wifi password is %s \n", pwd);

//     // ESP_ERROR_CHECK(esp_wifi_scan_stop());
//     // ESP_LOGI(TAG,"Wifi stop scaned");
//     nvs_init();
//     wifi_init_sta(wifiname, pwd);
//     // wifi_connect_sta(wifiname, pwd);
// }

// static void passwordtextarea_event_cb(lv_event_t *e)
// {
//     lv_event_code_t eventcode = lv_event_get_code(e);
//     lv_obj_t *ta = lv_event_get_target(e);

//     lv_obj_t *kb = ui_wifiKeyboard;
//     switch (eventcode)
//     {
//     case LV_EVENT_FOCUSED:
//         if (kb && ta)
//         {
//             lv_keyboard_set_textarea(kb, ta);
//             lv_obj_clear_flag(kb, LV_OBJ_FLAG_HIDDEN);
//         }
//         break;
//     case LV_EVENT_DEFOCUSED:
//         if (kb)
//         {
//             lv_keyboard_set_textarea(kb, NULL);
//             lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
//         }
//         break;

//     default:
//         break;
//     }
// }

void ui_wifipage_screen_init(void)
{
    ESP_LOGI(TAG,"WIFI配置界面初始化");
    // ESP_ERROR_CHECK(esp_netif_init());
    // ESP_ERROR_CHECK(esp_event_loop_create_default());
    // esp_netif_create_default_wifi_sta();


    ui_wifipage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifipage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifipage, lv_color_hex(0x5295B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifipage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifititle = lv_label_create(ui_wifipage);
    lv_obj_set_width(ui_wifititle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifititle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifititle, -115);
    lv_obj_set_y(ui_wifititle, 7);
    lv_obj_set_align(ui_wifititle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_wifititle, "WiFi扫描");
    lv_obj_set_style_text_color(ui_wifititle, lv_color_hex(0x353232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifititle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifititle, &ui_font_Terminal22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiDropdown = lv_dropdown_create(ui_wifipage);
    lv_obj_set_width(ui_wifiDropdown, 208);
    lv_obj_set_height(ui_wifiDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiDropdown, 30);
    lv_obj_set_y(ui_wifiDropdown, -59);
    lv_obj_set_align(ui_wifiDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // if (!wifiswitch_flag)
    // {
    //     lv_dropdown_clear_options(ui_wifiDropdown);
    // }


    ui_wifiswitch = lv_switch_create(ui_wifipage);
    lv_obj_set_width(ui_wifiswitch, 50);
    lv_obj_set_height(ui_wifiswitch, 25);
    lv_obj_set_x(ui_wifiswitch, -47);
    lv_obj_set_y(ui_wifiswitch, -102);
    lv_obj_set_align(ui_wifiswitch, LV_ALIGN_CENTER);
    // lv_obj_add_event_cb(ui_wifiswitch, switch_cb, LV_EVENT_CLICKED, NULL);

    ui_wifiled = lv_led_create(ui_wifipage);
    lv_obj_set_width(ui_wifiled, 25);
    lv_obj_set_height(ui_wifiled, 25);
    lv_obj_set_x(ui_wifiled, 160);
    lv_obj_set_y(ui_wifiled, 5);
    lv_led_off(ui_wifiled);
    lv_led_set_color(ui_wifiled, lv_palette_main(LV_PALETTE_GREEN));


    ui_usefulwifilabel = lv_label_create(ui_wifipage);
    lv_obj_set_width(ui_usefulwifilabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usefulwifilabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usefulwifilabel, -114);
    lv_obj_set_y(ui_usefulwifilabel, -58);
    lv_obj_set_align(ui_usefulwifilabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_usefulwifilabel, "可用WiFi：");
    lv_obj_set_style_text_color(ui_usefulwifilabel, lv_color_hex(0x33373A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_usefulwifilabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_usefulwifilabel, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordlabel = lv_label_create(ui_wifipage);
    lv_obj_set_width(ui_passwordlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_passwordlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_passwordlabel, -114);
    lv_obj_set_y(ui_passwordlabel, -22);
    lv_obj_set_align(ui_passwordlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_passwordlabel, "密        码：");
    lv_obj_set_style_text_color(ui_passwordlabel, lv_color_hex(0x313233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_passwordlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_passwordlabel, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordTextArea = lv_textarea_create(ui_wifipage);
    lv_obj_set_width(ui_passwordTextArea, 209);
    lv_obj_set_height(ui_passwordTextArea, 39);
    lv_obj_set_x(ui_passwordTextArea, 29);
    lv_obj_set_y(ui_passwordTextArea, -22);
    lv_obj_set_align(ui_passwordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordTextArea, "Placeholder...");
    // lv_obj_add_event_cb(ui_passwordTextArea, passwordtextarea_event_cb, LV_EVENT_ALL, ui_wifiKeyboard);


    ui_linkbtn = lv_btn_create(ui_wifipage);
    lv_obj_set_width(ui_linkbtn, 84);
    lv_obj_set_height(ui_linkbtn, 24);
    lv_obj_set_x(ui_linkbtn, 90);
    lv_obj_set_y(ui_linkbtn, -101);
    lv_obj_set_align(ui_linkbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_linkbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_linkbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_linkbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_linkbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_linklabel = lv_label_create(ui_linkbtn);
    lv_obj_set_width(ui_linklabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_linklabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_linklabel, -1);
    lv_obj_set_y(ui_linklabel, 1);
    lv_obj_set_align(ui_linklabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_linklabel, "连接");
    lv_obj_set_style_text_color(ui_linklabel, lv_color_hex(0x394952), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_linklabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_linklabel, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_add_event_cb(ui_linkbtn, wifi_linkbtn, LV_EVENT_CLICKED, NULL);

    ui_wifiKeyboard = lv_keyboard_create(lv_layer_top());
    lv_obj_set_width(ui_wifiKeyboard, 300);
    lv_obj_set_height(ui_wifiKeyboard, 120);
    lv_obj_set_x(ui_wifiKeyboard, 1);
    lv_obj_set_y(ui_wifiKeyboard, 57);
    lv_obj_set_align(ui_wifiKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiKeyboard, LV_OBJ_FLAG_HIDDEN);

    lv_obj_set_style_bg_color(ui_wifiKeyboard, lv_color_hex(0xABD1E3), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifiKeyboard, ui_event_wifiKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifipage, ui_event_wifipage, LV_EVENT_ALL, NULL);

}
