// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Terminal

#include "../ui.h"

void ui_weatherpage_screen_init(void)
{
    ui_weatherpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weatherpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_weatherpage);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "天气");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Terminal, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_weatherpage, ui_event_weatherpage, LV_EVENT_ALL, NULL);

}
